services:
  python_service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: workshop1
    container_name: workshop_python_container
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  postgres:
    image: postgres:latest
    container_name: psql-d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workshop
    ports:
      - "5432:5432"
